mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

mysite/posts/urls.py
from django.urls import path
from . import views, api
app_name = "posts"
urlpatterns = [
    path('', views.index, name="index"),
    path('api/posts/', api.PostViewset.as_view({"get":"list", "post": "create"})),
    path('api/posts/<int:pk>', api.PostViewset.as_view({"get":"retrieve", "post":"update"})),
    path('<int:id>/', views.postDetails, name="details"),
    # path('api/posts/create', api.createPost, name="create-post"),
    # path('api/posts/', api.listPosts, name="posts-list"),
    # path('api/posts/<int:id>', api.postDetail, name="post-detail"),
    # path('api/posts/<int:id>/update/', api.updatePost, name="update-post"),
    # path('api/posts/<int:id>/delete/', api.deletePost, name="delete-post"),
]

mysite/posts/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title= models.CharField(max_length=200, default="")
    body= models.TextField(default="")

    pub_data= models.DateTimeField("publish date", default=timezone.now())

    def __str__(self):
        return self.title

class Comment(models.Model):
    text = models.TextField(default="")
    likes = models.IntegerField(default=0)

    post=models.ForeignKey('Post', on_delete=models.CASCADE,)

    def __str__(self):
        return self.text

mysite/posts/views.py
from .models import Post, Comment
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

# Create your views here.
def index(req):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(req, 'posts/index.html', context=context)

def postDetails(req, id):
    try:
        post = Post.objects.get(pk=id)
    except Post.DoesNotExist:
        raise Http404("Post does not exist")
    return render(req, 'posts/details.html', context={ 'post': post })

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>mySite {% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

mysite/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">myApp</a>
	</div>
</nav>

mysite/templates/posts/details.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'posts:index' %}">Back To Posts</a>
<h1 class="text-center mb-3">{{ post.title }}</h1>
<p>{{ post.body }}</p>
{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}
    <h4>Comments on this post</h4>
	{% for comment in post.comment_set.all %}
	<p>{{ comment.text }}</p>
	{% endfor %}
	
{% endblock %}

mysite/templates/posts/index.html
{% extends 'base.html' %} 
{% block content %} 

<h1 class="text-center mb-3">Posts</h1>
  {% if posts %}
    {% for post in posts %}
      <div class="card mb-3">
        <div class="card-body">
            <h3>{{ post.title }}</h3>
          <p class="lead">{{ post.body }}</p>
          <a href="{% url 'posts:details' post.id %}" class="btn btn-primary btn-sm">details</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No Post available</p>
  {% endif %}
{% endblock %}